	<div id="sideBar">
	<ul>
		<li><a href='http://helios.ite.gmu.edu/~revans17/IT%20207/'>Home Page</a></li>
	</ul>
		<strong>Lab Assignments</strong>
		<ul>
			<li><a href='http://helios.ite.gmu.edu/~revans17/IT%20207/Lab1/Assingment1Home.php'>Lab One</a></li>
			<li><a href='http://helios.ite.gmu.edu/~revans17/IT%20207/Lab2/'>Lab Two</a></li>
			<li><a href='http://helios.ite.gmu.edu/~revans17/IT%20207/Lab3/'>Lab Three</a></li>
			<li><a href='http://helios.ite.gmu.edu/~revans17/IT%20207/Lab4/'>Lab Four</a></li>
		</ul>
		<strong>Lab Practica</strong>
		<ul>
			<li><a href='http://helios.ite.gmu.edu/~revans17/IT%20207/Practica1/'>Practica One</a></li>
			<li><a href='http://helios.ite.gmu.edu/~revans17/IT%20207/Practica2/'>Practica Two</a></li>
		</ul>
	</div> 